from __future__ import annotations

import os

import pytest


RUNTIME_ENV_KEYS = (
    "GLASSHIVE_ENTERPRISE_MODE",
    "GLASSHIVE_AUTH_MODE",
    "GLASSHIVE_ENTERPRISE_TENANT_ID",
    "GLASSHIVE_AUTH_USER_HEADER",
    "GLASSHIVE_AUTH_EMAIL_HEADER",
    "GLASSHIVE_AUTH_ROLE_HEADER",
    "GLASSHIVE_AUTH_TENANT_HEADER",
    "GLASSHIVE_HOST_WORKERS_ENABLED",
    "GLASSHIVE_HOST_RUNTIME_REQUIREMENTS_JSON",
    "GLASSHIVE_HOST_RUNTIME_REQUIREMENTS_FILE",
    "WPR_HOST_RUNTIME_REQUIREMENTS_JSON",
    "WPR_HOST_RUNTIME_REQUIREMENTS_FILE",
    "GLASSHIVE_HOST_CODEX_NATIVE_MCP_ALLOWLIST",
    "WPR_HOST_CODEX_NATIVE_MCP_ALLOWLIST",
    "GLASSHIVE_HOST_CODEX_PLUGIN_CACHE",
    "WPR_HOST_CODEX_PLUGIN_CACHE",
    "GLASSHIVE_AUTO_DISCOVER_CODEX_WORKSPACE_DEPS",
    "WPR_AUTO_DISCOVER_CODEX_WORKSPACE_DEPS",
    "GLASSHIVE_CODEX_WORKSPACE_DEPS_ROOT",
    "WPR_CODEX_WORKSPACE_DEPS_ROOT",
    "GLASSHIVE_WORKSPACE_NODE_MODULES",
    "WPR_WORKSPACE_NODE_MODULES",
    "GLASSHIVE_WORKSPACE_NODE_BIN",
    "WPR_WORKSPACE_NODE_BIN",
    "GLASSHIVE_WORKSPACE_PYTHON_BIN",
    "WPR_WORKSPACE_PYTHON_BIN",
    "GLASSHIVE_WORKSPACE_BIN_DIRS",
    "WPR_WORKSPACE_BIN_DIRS",
    "GLASSHIVE_IDLE_TERMINATE_AFTER_S",
    "GLASSHIVE_PAUSED_TERMINATE_AFTER_S",
    "GLASSHIVE_IDLE_REAPER_INTERVAL_S",
    "GLASSHIVE_MAX_RUN_DURATION_S",
    "GLASSHIVE_MAX_WATCH_SESSION_DURATION_S",
    "GLASSHIVE_ARTIFACT_DOWNLOAD_MAX_BYTES",
    "GLASSHIVE_ENABLE_ADMIN_API",
    "GLASSHIVE_PROJECT_PROVIDER_ENV",
    "GLASSHIVE_WORKER_SECRET_ENV_EXPOSURE",
    "GLASSHIVE_WORKER_SECRET_ENV_KEYS",
    "GLASSHIVE_SIGNED_LINK_SECRET",
    "GLASSHIVE_LINK_REF_STATE_PATH",
    "GLASSHIVE_LINK_REF_TTL_SECONDS",
    "GLASSHIVE_WORKER_ENV_ALLOWLIST",
    "GLASSHIVE_ALLOWED_WORKER_PROFILES",
    "GLASSHIVE_DEFAULT_WORKER_PROFILE",
    "WPR_API_TOKEN",
    "WPR_DB_PATH",
    "WPR_LINK_REF_TTL_SECONDS",
    "WPR_DEFAULT_EXECUTION_MODE",
    "WPR_ENTERPRISE_MODE",
    "WPR_ENTERPRISE_TENANT_ID",
    "WPR_LIBRECHAT_UPLOADS_ROOT",
    "WPR_BOOTSTRAP_SOURCE_ROOTS",
    "WPR_RUNTIME_BACKEND",
    "WPR_ALLOWED_WORKER_PROFILES",
    "WPR_CODEX_CLI_REASONING_EFFORT",
    "WPR_CODEX_CLI_BASE_URL",
    "WPR_CODEX_CLI_PROVIDER_NAME",
    "WPR_CODEX_CLI_DISABLE_CUSTOM_PROVIDER",
    "WPR_CODEX_CLI_IGNORE_USER_CONFIG",
    "WPR_CODEX_CLI_DISABLE_FEATURES",
    "WPR_CODEX_BIN",
    "WPR_CLAUDE_CODE_BIN",
    "WPR_CLAUDE_CODE_ENABLE_CHROME",
    "WPR_CLAUDE_CODE_EFFORT",
    "WPR_OPENCLAW_BIN",
    "VIVENTIUM_ENV_FILE",
)


os.environ.setdefault("VIVENTIUM_DISABLE_DEFAULT_RUNTIME_ENV", "1")
for key in RUNTIME_ENV_KEYS:
    os.environ.pop(key, None)


@pytest.fixture(autouse=True)
def isolate_runtime_env(monkeypatch: pytest.MonkeyPatch, tmp_path):
    for key in RUNTIME_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)
    monkeypatch.setenv("GLASSHIVE_LINK_REF_STATE_PATH", str(tmp_path / "link_refs.sqlite3"))
    yield
